#!/bin/bash
# Lu et al. neural-PK baseline on the scenario-4 benchmark, paper-level noise, N = 100 training patients.
# Two variants x seeds 1-3, 6000 epochs, fixed-epoch checkpoints (traj/ every 300), per-seed save roots
# (the checkpoint name carries no seed: handoff landmine 1.4). Then scores ep6000 on the same test
# patients as OT-FiLM / dose-cond (in range, below, above; scaler pinned to the training cohort) and on
# the training cohort (--eval-split all, for the training-set recalibration factor).
#   faithful : Lu et al.'s procedure -- encoder sees only the 4 dynamic features, reconstruct-only loss
#   static   : + static covariates (dose, formulation, CYP, HT) in the encoder, + cross-visit loss
# Log: logs/chain_lu.log. Do not edit this file while it runs (bash reads scripts incrementally).
cd /Users/benjaminmaurel/Documents/PharmaNODE
PY=/opt/miniconda3/bin/python3.12
T=confound_vc00_s4_pnoise_n100; B=confound_vc00_s4_pnoise; R=results/s4_pnoise_lu; RC=results/recal/paper_lu
SEEDS="${SEEDS:-1 2 3}"; NIT=${NIT:-6000}
mkdir -p $R/eval $RC logs
say () { echo "[$(date '+%F %T')] $*"; }
flags () { [ "$1" = faithful ] && echo "--static-dim 4" || echo "--static-dim 4 --use-static --train-mode counterfactual"; }
tag ()   { [ "$1" = faithful ] && echo "__sdim-4" || echo "__mode-counterfactual_static_sdim-4"; }

PIDS=""
for v in static faithful; do          # longest first
  for s in $SEEDS; do
    OMP_NUM_THREADS=1 nohup $PY -W ignore train_lu_pk.py --experiment $T --data-dir ./results/exp_film_run \
      --niters $NIT -b 512 --seed $s --save ./$R/${v}_n100_s$s/ --ckpt-every 300 --eval-every 300 \
      $(flags $v) > logs/train_lu_${v}_n100_s$s.log 2>&1 &
    PIDS="$PIDS $!"; say "launched $v seed $s (pid $!)"
    sleep 2
  done
done
echo "$PIDS" > logs/lu_pnoise.pids
wait $PIDS
say "training finished; scoring ep$(printf %06d $NIT)"

score_one () {  # variant seed
  v=$1; s=$2; ep=$(printf %06d $NIT)
  CK=$R/${v}_n100_s$s/exp_lupk_run/$T/traj/experiment_lupk_$T$(tag $v)_ep$ep.ckpt
  [ -f "$CK" ] || { say "MISSING $CK"; return; }
  for reg in "" _lo _hi; do
    nm=${reg#_}; nm=${nm:-in}
    OMP_NUM_THREADS=1 $PY -W ignore test_lu_pk.py --experiment $B$reg --scale-from $T --ckpt $CK \
      --label lu_${v}_s$s$reg --out-json $R/eval/ep${ep}_lu-${v}_n100_s${s}_on_$nm.json \
      > logs/eval_lu_${v}_n100_s$s$reg.log 2>&1
  done
  OMP_NUM_THREADS=1 $PY -W ignore test_lu_pk.py --experiment $T --scale-from $T --eval-split all --ckpt $CK \
    --label lu_${v}_all_s$s --out-json $RC/${v}_s${s}_all.json > logs/recal_lu_${v}_s$s.log 2>&1
  say "scored $v seed $s"
}
for v in faithful static; do
  for s in $SEEDS; do score_one $v $s & done
  wait
done
say "LU_PNOISE_DONE"
